version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - 'npm install'
  build:
    commands:
      - 'npm run recursive-install'
      - 'npm run build'
      - 'npm run cdk synth -- -o dist'